# Generated by Django 3.2.25 on 2024-04-08 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240404_0236'),
        ('products', '0003_product_has_sizes'),
    ]

    operations = [
    ]
