# Generated by Django 5.0.3 on 2024-04-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_0002_auto_20240404_0236_0003_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_protein',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
